<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE world
[
<!ELEMENT region (country+)>
<!ELEMENT country (university+)>
<!ELEMENT university (department+, rank+)>
<!ATTLIST university
    code ID#REQUIRED
    name CDATA#REQUIRED
>
<!ELEMENT department (degree+, rank+)>
<!ELEMENT rank (type)>
<!ATTLIST rank
    name (ARWU|QS)
>
<!ELEMENT type (#PCDATA)>

<!ELEMENT degree (#PCDATA)>
]>

<world>
  <region>Asia</region>
    <country>Singapore</country>
  <region>Europe</region>
    <country>UK</country>
  <region>America</region>
    <country>US</country>
  <region>Australia</region>
    <country>Australia</country>
  <region>Africa</region>
    <country>South Africa</country>
</world>
